### ISSUE TITLE
*EPIC* To do

### ISSUE THREAD

**Issue by lucyrose93** [lucyrose93/MakaTalk#91]
UI (Lucy)
- [ ] mobile responsive
- [ ] backgrounds still weird
- [ ] back button 
- [ ] click through
- [x] style results page 

BACKEND
- [ ] Clinician usernames/pwords database
- [ ] Email results to clinician function

VIDEOS
- [ ] Image thumbnails to replace video options (Martha)
- [ ] Logic for playing videos (Martha)
